[package]
name = "urd-compiler"
version = "0.1.3"
edition = "2021"
description = "Five-phase compiler for Urd Schema Markdown (.urd.md â†’ .urd.json)"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
wasm = ["wasm-bindgen"]

[dependencies]
indexmap = "2"
serde_json = { version = "1", features = ["preserve_order"] }
wasm-bindgen = { version = "0.2", optional = true }

[[bin]]
name = "urd"
path = "src/bin/main.rs"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[profile.release]
opt-level = 3
lto = true

[dev-dependencies]
